version: '3'

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-socialmedia"
    restart: always
    volumes:
      - ./db-socialmedia:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg

volumes:
  db-socialmedia: